### ISSUE TITLE
sprite viewer adjustments

### ISSUE THREAD

**Issue by amitch3** [DCAN-Labs/ExecutiveSummary#8]
with the next update of the nhp pipeline, could the sprite viewer specifications be altered so that each image has the same dimensions as the sagittal view? I have detailed a snapshot of the current view(s) below. 

![image](https://user-images.githubusercontent.com/41393207/79076461-2334b800-7caf-11ea-82f6-f42a33fd7bf3.png)

**Comment by kathy-snider** [comment]
I will look into this. It will probably require an option passed in, since it should probably only apply to monkeys (the human brainsprites do not look like this), but it's possible there is something else going on.
