### ISSUE TITLE
Add Swipes For Science images

### ISSUE THREAD

**Issue by ericearl** [DCAN-Labs/ExecutiveSummary#9]
We would like to save all the Swipes For Science data to Executive Summaries (including surface delineations which may not appear in the executive summary pages themselves).  This will make doing Swipes For Science data prep easier.

**Comment by perronea** [comment]
We also need to write in some code to reformat some of the "slices" images to be a grid instead of a row specifically for viewing in SFS.

**Comment by kathy-snider** [comment]
So will one of you add the issue(s) to Executive Summary with enough explanation for me to make the changes? Who knows, I might get to this someday!


________________________________
